### ISSUE TITLE
Barre d'outil en front

### ISSUE THREAD

**Issue by AntoineCabrol** [AntoineCabrol/antenneFFMC#37]
## Descriptif rapide
Ajout d'une barre d'outil en front visible lorsqu'on est connecté, qui apporte des raccourcis et informations spécifiques supplémentaires à l'antenne.

## Fonctionnalités

Statuts concernés : 
⚪️ tous les auteurs
🔵 administrateurs uniquement
🔴 webmestres uniquement

### Résumé :
- [ ] ⚪️ signalement d'un bug (issue #43)
- [ ] ⚪️ documentation relative aux éléments sur la page qui en ont une (issue #44)
- [ ] 🔴 informations essentielles sur la config du site (issue #45)

---
Suivi :
@AntoineCabrol 1
@Norbert73 0.25

**Comment by AntoineCabrol** [comment]
@Norbert73, qu'est-ce que tu penses utile d'ajouter ou que tu vois à corriger ?

**Comment by AntoineCabrol** [comment]
Ça serait bien d'intégrer les derniers articles de la preprod, soit dans une info bulle dans la toolbar, soit dans le BO du plugin sur la page d'accueil, soit aux 2 endroits !

**Comment by Norbert73** [comment]
Oui, bonne idée ! 
Ok pour intégrer les derniers articles de la preprod dans le BO du plugin et non, pas dans la toolbar.

**Comment by Norbert73** [comment]
Antoine,Oui, bonne idée !Bisousenvoyé : 27 avril 2020 à 14:43de : Antoine Cabrol <notifications@github.com>à : AntoineCabrol/antenneFFMC <antenneFFMC@noreply.github.com>cc : Norbert73 <cabrol.norbert@orange.fr>, Assign <assign@noreply.github.com>objet : [AntoineCabrol/antenneFFMC] Feature - Barre d'outil en front (#37) Descriptif rapideAjout d'une barre d'outil en front visible lorsqu'on est connecté, qui apporte des raccourcis et informations spécifiques supplémentaires à l'antenne.FonctionnalitésStatuts concernés : ⚪️ tous les auteurs 🔵 administrateurs uniquement 🔴 webmestres uniquementRésumé :⚪️ signalement d'un bug⚪️ documentation relative aux éléments sur la page qui en ont une🔴 informations essentielles sur la config du siteDétailsSignalement d'un bugEnvoi rapide d'un message auquel pour décrire un problème, avec mini formulaire pour aider la prise en charge : ➝ navigateur(s) testé(s) ➝ mode(s) testé(s) (connecté/déconnecté) ➝ possibilité de sélectionner un élément dans la pageDocumentationListe des éléments de documentation basée sur les éléments présents sur la page qui en ont une. Lien vers la page de documentation correspondante dans la doc intégrée du plugin en BO.Informations essentielles sur la configAffichage de l'hébergeur, la version de php, la version du plugin.. (besoins à affiner)—You are receiving this because you were assigned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by AntoineCabrol** [comment]
Parfait merci pour ton retour !
Pour les derniers articles de la preprod, j'ai créé une issue #39 dédiée.
